# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'OurPlanet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OurPlanet
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'


end
